const ManufacturerActionTypes = {
  FETCH_MANUFACTURERS_START: 'FETCH_MANUFACTURERS_START',
  FETCH_MANUFACTURERS_SUCCESS: 'FETCH_MANUFACTURERS_SUCCESS',
  FETCH_MANUFACTURERS_FAILURE: 'FETCH_MANUFACTURERS_FAILURE',
};

export default ManufacturerActionTypes;
