export const SIGN_IN = 'SIGN_IN';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIDER_SET_OPEN_KEYS = 'SIDER_SET_OPEN_KEYS';

export const FETCH_MANUFACTURERS = 'FETCH_MANUFACTURERS';

export const FETCH_MANUFACTURERS_SUCCESS = 'FETCH_MANUFACTURERS_SUCCESS';

export const FETCH_SERVICE_TYPES = 'FETCH_SERVICE_TYPES';

export const FETCH_SERVICE_TYPES_SUCCESS = 'FETCH_SERVICE_TYPES_SUCCESS';

export const FETCH_MODELS = 'FETCH_MODELS';

export const FETCH_MODELS_SUCCESS = 'FETCH_MODELS_SUCCESS';

export const INIT_MODIFY_SERVICE = 'INIT_MODIFY_SERVICE';

export const INIT_MODIFY_SERVICE_SUCCESS = 'INIT_MODIFY_SERVICE_SUCCESS';

export const INIT_MODIFY_SERVICE_WITH_PARTS = 'INIT_MODIFY_SERVICE_WITH_PARTS';

export const FETCH_SERVICE_SECTIONS = 'FETCH_SERVICE_SECTIONS';

export const FETCH_SERVICE_SECTIONS_SUCCESS = 'FETCH_SERVICE_SECTIONS_SUCCESS';

export const FETCH_PARTS = 'FETCH_PARTS';

export const FETCH_PARTS_SUCCESS = 'FETCH_PARTS_SUCCESS';

export const FETCH_PART_SECTIONS_WITH_CATEGORIES =
  'FETCH_PART_SECTIONS_WITH_CATEGORIES';

export const FETCH_PART_SECTIONS_WITH_CATEGORIES_SUCCESS =
  'FETCH_PART_SECTIONS_WITH_CATEGORIES_SUCCESS';
