export const SIGN_IN = 'SIGN_IN';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIDER_SET_OPEN_KEYS = 'SIDER_SET_OPEN_KEYS';

export const SIGN_OUT = 'SIGN_OUT';

export const FETCH_MANUFACTURERS = 'FETCH_MANUFACTURERS';

export const FETCH_MANUFACTURERS_SUCCESS = 'FETCH_MANUFACTURERS_SUCCESS';

export const FETCH_SERVICE_TYPES = 'FETCH_SERVICE_TYPES';

export const FETCH_SERVICE_TYPES_SUCCESS = 'FETCH_SERVICE_TYPES_SUCCESS';

export const FETCH_MODELS = 'FETCH_MODELS';

export const FETCH_MODELS_SUCCESS = 'FETCH_MODELS_SUCCESS';

export const INIT_MODIFY_SERVICE = 'INIT_MODIFY_SERVICE';

export const INIT_UPDATE_SERVICE = 'INIT_UPDATE_SERVICE';

export const INIT_UPDATE_SERVICE_WITH_PARTS = 'INIT_UPDATE_SERVICE_WITH_PARTS';

export const INIT_MODIFY_SERVICE_WITH_PARTS = 'INIT_MODIFY_SERVICE_WITH_PARTS';

export const FETCH_SERVICE_SECTIONS = 'FETCH_SERVICE_SECTIONS';

export const FETCH_SERVICE_SECTIONS_SUCCESS = 'FETCH_SERVICE_SECTIONS_SUCCESS';

export const FETCH_PARTS = 'FETCH_PARTS';

export const FETCH_PARTS_SUCCESS = 'FETCH_PARTS_SUCCESS';

export const FETCH_PART_SECTIONS_WITH_CATEGORIES =
  'FETCH_PART_SECTIONS_WITH_CATEGORIES';

export const FETCH_PART_SECTIONS_WITH_CATEGORIES_SUCCESS =
  'FETCH_PART_SECTIONS_WITH_CATEGORIES_SUCCESS';

export const INIT_UPDATE_REQUEST = 'INIT_UPDATE_REQUEST';

export const RESET_UPDATE_REQUEST = 'RESET_UPDATE_REQUEST';

export const FETCH_SERVICES_BY_PROVIDER_AND_TYPE =
  'FETCH_SERVICES_BY_PROVIDER_AND_TYPE';

export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const ADD_SERVICE_TO_REQUEST = 'ADD_SERVICE_TO_REQUEST';

export const REMOVE_SERVICE_FROM_REQUEST = 'REMOVE_SERVICE_FROM_REQUEST';

export const REMOVE_EXPENSE_FROM_REQUEST = 'REMOVE_EXPENSE_FROM_REQUEST';

export const ADD_EXPENSE_TO_REQUEST = 'ADD_EXPENSE_TO_REQUEST';

export const UPDATE_REQUEST = 'UPDATE_REQUEST';

export const FETCH_REQUESTS = 'FETCH_REQUESTS';

export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';

export const UPDATE_EXPENSE_TO_REQUEST = 'UPDATE_EXPENSE_TO_REQUEST';

export const CHECK_IN_REQUEST = 'CHECK_IN_REQUEST';

export const CONFIRM_REQUEST = 'CONFIRM_REQUEST';

export const COMPLETE_REQUEST = 'COMPLETE_REQUEST';

export const CHECK_OUT_REQUEST = 'CHECK_OUT_REQUEST';

export const CANCEL_REQUEST = 'CANCEL_REQUEST';

export const UPDATE_PARTS_IN_REQUEST_SERVICE =
  'UPDATE_PARTS_IN_REQUEST_SERVICE';
