const RequestActionTypes = {
  FETCH_REQUESTS_START: 'FETCH_REQUESTS_START',
  FETCH_REQUESTS_SUCCESS: 'FETCH_REQUESTS_SUCCESS',
  FETCH_REQUESTS_FAILURE: 'FETCH_REQUESTS_FAILURE',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
  CHECK_IN_REQUEST_START: 'CHECK_IN_REQUEST_START',
  CHECK_IN_REQUEST_SUCCESS: 'CHECK_IN_REQUEST_SUCCESS',
  CHECK_IN_REQUEST_FAILURE: 'CHECK_IN_REQUEST_FAILURE',
  FETCH_AVAILABLE_TECHNICIANS_START: 'FETCH_AVAILABLE_TECHNICIANS_START',
  FETCH_AVAILABLE_TECHNICIANS_SUCCESS: 'FETCH_AVAILABLE_TECHNICIANS_SUCCESS',
  FETCH_AVAILABLE_TECHNICIANS_FAILURE: 'FETCH_AVAILABLE_TECHNICIANS_FAILURE',
  CONFIRM_REQUEST_START: 'CONFIRM_REQUEST_START',
  CONFIRM_REQUEST_SUCCESS: 'CONFIRM_REQUEST_SUCCESS',
  CONFIRM_REQUEST_FAILURE: 'CONFIRM_REQUEST_FAILURE',
  COMPLETE_REQUEST_START: 'COMPLETE_REQUEST_START',
  COMPLETE_REQUEST_SUCCESS: 'COMPLETE_REQUEST_SUCCESS',
  COMPLETE_REQUEST_FAILURE: 'COMPLETE_REQUEST_FAILURE',
  CHECKOUT_REQUEST_START: 'CHECKOUT_REQUEST_START',
  CHECKOUT_REQUEST_SUCCESS: 'CHECKOUT_REQUEST_SUCCESS',
  CHECKOUT_REQUEST_FAILURE: 'CHECKOUT_REQUEST_FAILURE',
};

export default RequestActionTypes;
