const CategoryActionTypes = {
  FETCH_SECTIONS_WITH_CATEGORIES_START: 'FETCH_SECTIONS_WITH_CATEGORIES_START',
  FETCH_SECTIONS_WITH_CATEGORIES_SUCCESS:
    'FETCH_SECTIONS_WITH_CATEGORIES_SUCCESS',
  FETCH_SECTIONS_WITH_CATEGORIES_FAILURE:
    'FETCH_SECTIONS_WITH_CATEGORIES_FAILURE',
};

export default CategoryActionTypes;
