const PartActionTypes = {
  FETCH_PARTS_START: 'FETCH_PARTS_START',
  FETCH_PARTS_SUCCESS: 'FETCH_PARTS_SUCCESS',
  FETCH_PARTS_FAILURE: 'FETCH_PARTS_FAILURE',
  LOAD_PART_FORM_START: 'LOAD_PART_FORM_START',
  LOAD_PART_FORM_SUCCESS: 'LOAD_PART_FORM_SUCCESS',
  LOAD_PART_FORM_FAILURE: 'LOAD_PART_FORM_FAILURE',
  SHOW_PART_MODAL: 'SHOW_PART_MODAL',
  CLOSE_PART_MODAL: 'CLOSE_PART_MODAL',
  CREATE_PART_START: 'CREATE_PART_START',
  CREATE_PART_SUCCESS: 'CREATE_PART_SUCCESS',
  CREATE_PART_FAILURE: 'CREATE_PART_FAILURE',
  UPDATE_PART_START: 'UPDATE_PART_START',
  UPDATE_PART_SUCCESS: 'UPDATE_PART_SUCCESS',
  UPDATE_PART_FAILURE: 'UPDATE_PART_FAILURE',
};

export default PartActionTypes;
