const ModelActionTypes = {
  FETCH_MODELS_START: 'FETCH_MODELS_START',
  FETCH_MODELS_SUCCESS: 'FETCH_MODELS_SUCCESS',
  FETCH_MODELS_FAILURE: 'FETCH_MODELS_FAILURE',
  FETCH_MANUFACTURERS_AND_MODELS: 'FETCH_MANUFACTURERS_AND_MODELS',
};

export default ModelActionTypes;
