const PackageActionTypes = {
  FETCH_PACKAGES_START: 'FETCH_PACKAGES_START',
  FETCH_PACKAGES_SUCCESS: 'FETCH_PACKAGES_SUCCESS',
  FETCH_PACKAGES_FAILURE: 'FETCH_PACKAGES_FAILURE',
  LOAD_PACKAGE_FORM_START: 'LOAD_PACKAGE_FORM_START',
  LOAD_PACKAGE_FORM_SUCCESS: 'LOAD_PACKAGE_FORM_SUCCESS',
  LOAD_PACKAGE_FORM_FAILURE: 'LOAD_PACKAGE_FORM_FAILURE',
  FETCH_MILESTONES_START: 'FETCH_MILESTONES_START',
  FETCH_MILESTONES_SUCCESS: 'FETCH_MILESTONES_SUCCESS',
  FETCH_MILESTONES_FAILURE: 'FETCH_MILESTONES_FAILURE',
  CREATE_PACKAGE_START: 'CREATE_PACKAGE_START',
  CREATE_PACKAGE_SUCCESS: 'CREATE_PACKAGE_SUCCESS',
  CREATE_PACKAGE_FAILURE: 'CREATE_PACKAGE_FAILURE',
  UPDATE_PACKAGE_START: 'UPDATE_PACKAGE_START',
  UPDATE_PACKAGE_SUCCESS: 'UPDATE_PACKAGE_SUCCESS',
  UPDATE_PACKAGE_FAILURE: 'UPDATE_PACKAGE_FAILURE',
  REMOVE_PACKAGE_START: 'REMOVE_PACKAGE_START',
  REMOVE_PACKAGE_SUCCESS: 'REMOVE_PACKAGE_SUCCESS',
  REMOVE_PACKAGE_FAILURE: 'REMOVE_PACKAGE_FAILURE',
  FETCH_PACKAGES_BY_MODEL_START: 'FETCH_PACKAGES_BY_MODEL_START',
};

export default PackageActionTypes;
