const UserActionTypes = {
  FETCH_USERS_START: 'FETCH_USERS_START',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  CREATE_USER_START: 'CREATE_USER_START',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  TOGGLE_USER_ACTIVE_START: 'TOGGLE_USER_ACTIVE_START',
  TOGGLE_USER_ACTIVE_SUCCESS: 'TOGGLE_USER_ACTIVE_SUCCESS',
  TOGGLE_USER_ACTIVE_FAILURE: 'TOGGLE_USER_ACTIVE_FAILURE',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
};

export default UserActionTypes;
